### ISSUE TITLE
decodeURIComponent fails with 'URI malformed' error

### ISSUE THREAD

**Issue by mikhailv** [ScottHamper/Cookies#22]
In Google Chrome, if input data is incorrect, '_decodeURIComponent_' method throws an exception with error string '**URIError: URI malformed**'. This error causes cookie reading through 'Cookies' to stop working.

**Actual behavior**: code throws an error

**Expected behavior**: cookies with incorrect value not being returned. (possible solution: catch errors when '__getKeyValuePairFromCookieString_' function is called or add error handling callback to Cookies API)

**Environment**: Chrome 33

To reproduce this error: invoke 'decodeURIComponent('%D0%EE%F1%F1%E8%FF')' in Chrome 33

**Comment by rymai** [comment]
Hello @ScottHamper!

We're in the same situation as @mikhailv and I think that's a shame that `cookies-js` is not robust enough and cannot handle malencoded cookies. As @mikhailv proposed, the lib could simply ignore such cookies **without any fallback to `unescape`** and everything would be fine.
The end-result would be better than now: skip a malencoded cookie and not crash the page instead of trying to decode a malencoded cookie and crash the page.

Would you be interested in a pull-request toward that goal?

**Comment by ScottHamper** [comment]
Hey @rymai ,

I recognize the problem of being unable to read any cookies if there's only a single malformed cookie. This is definitely not ideal, and we can come up with a better solution. However, I consider silent failures to be poor practice, as they make debugging more difficult. The documentation for Cookies.js clearly lays out the expectations for encoding, and a malformed cookie value should be considered an error.

So it seems to me that the real issue is not that an error is thrown, but that an error is thrown regardless of whether or not the user is trying to access a malformed cookie. The reason this happens today is because Cookies.js attempts to parse/decode/cache the entire `document.cookie` string before returning the requested cookie value.

A more ideal implementation would be one which lazily decodes cookie values, so that the only time an error occurs is when the user attempts to read a malformed cookie. This approach could still have a complete failure if any cookie *key* is malformed, but would solve the issue for malformed values.

Solving the issue for malformed keys is tricker, as there's no way we can lazily decode any specific key. The best solution I can think of would be to use a try/catch like you guys have proposed for values, but then use `console.error` if it exists in the current browser in order to avoid silent failures (where possible). Ideally, there would be a way to let the error throw as normal, but continue execution afterwards. I can't think of a way to accomplish this, though, so `console.error` seems like the best compromise.

In any case, I can spend some time working on this later today. Let me know what your thoughts are, and if you have any other ideas for solutions that could be more ideal.
