### ISSUE TITLE
Bump version for npm update

### ISSUE THREAD

**Issue by Autarc** [ScottHamper/Cookies#33]
The current version at npm/bower points to 1.1.0 although it got the additional feature to pass the 'Infinity' expiration since last month (see 738ebf0). Their referenced version is therefore out of sync and throws an error if not passing a valid date or number. As its going to be confusing for others - I recommend to publish a minor upgrade with the latest changes.

**Comment by juice49** [comment]
This is an issue I have just bumped into, it appears the npm package is still behind.

**Comment by ScottHamper** [comment]
Hey guys,

It's published finally. I can understand the confusion - I've been using master as the main development branch, so just because something is implemented in master doesn't mean that it will be in the latest release (NPM wasn't out of date/sync - a release was never made). This is def confusing though when someone comes to the repo and reads the API reference for master instead of the latest release.

I had originally intended to make more changes before publishing a release, but everything got put on the back burner. This release has been way overdue as a result. Sorry about that!

In the future, I will likely avoid this type of confusion by using a separate dev branch and having master simply reflect the latest release.

Thanks for checking out the library!
