### ISSUE TITLE
Provide option to select which document

### ISSUE THREAD

**Issue by cobbdb** [ScottHamper/Cookies#36]
It would be nice for sites that use friendly iframes to specify which document is used:
```
window.document.cookie
```
vs
```
window.top.document.cookie
```

**Comment by ScottHamper** [comment]
Hey Dan,

Could you explain your use case a little more so that I can get a better understanding of what you're trying to do?

It's my understanding that both the top document and the iframe would need to be on the same domain in order to do what you're describing (due to same-origin policy). If that's the case, there should not be any need to specify which document to use for Cookies.js. By setting a cookie for the domain, regardless of which document you used to set the cookie, both documents should be able to retrieve the cookie value.

Alternatively, consider including Cookies.js in both the top document and the iframe and simply do something like `window.top.Cookies.set(...)`. Or use [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window.postMessage) for more complicated/cross-origin situations. This issue does not seem like a responsibility that Cookies.js should be taking on.
