### ISSUE TITLE
Add 'raw' parameter

### ISSUE THREAD

**Issue by bradvogel** [ScottHamper/Cookies#44]
It'd be nice to have a 'raw' parameter like https://github.com/aralejs/cookie has that bypasses encoding when setting a cookie.

**Comment by bradvogel** [comment]
The use case is just interoperating with old backends that didn't encode cookies.

**Comment by ScottHamper** [comment]
Hey Brad,

Thanks for checking out the library! I understand how this functionality could be useful in certain cases, but I don't like the idea of complicating the API and optionally breaking compatibility with RFC6265 in order to support legacy environments. It should not be the responsibility of Cookies.js to work around the inability to change a backend system.
