### ISSUE TITLE
Share cookie data between two different domain 

### ISSUE THREAD

**Issue by cullsin** [ScottHamper/Cookies#66]
Hi, 

I have a question about sharing data between two different domains. 
Does it possible through cookies ?

Can you suggest me on this.

Raja K

**Comment by ScottHamper** [comment]
Nope, not possible due to the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Cross-origin_data_storage_access).

You can have two different *sub-*domains access a cookie that was set for their same parent domain, but you cannot have two completely different domains sharing cookies with one another.
